spring:
  profiles:
    active: dev
  application:
    name: waiting_reservation_be
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/reservation?useUnicode=true&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  thymeleaf:
    cache: false

logging:
  config: classpath:logback-spring.xml